### ISSUE TITLE
Feature - Remember password/Stay logged in 

### ISSUE THREAD

**Issue by Zukye** [DivineThreepwood/bcozy#11]
Implement feature to remember password and keep user logged in.

**Comment by DivineThreepwood** [comment]
Backend functionallity has been implemented. Only the checkbox is missing in bcozy "stay logged in" but it can already be used by the bco.visual.remote.

Removed from epic because this is not a part of the core framework.

**Comment by DivineThreepwood** [comment]
bcozy development has been freezed.
