### ISSUE TITLE
Introduce SystemUserFlag in UserConfig

### ISSUE THREAD

**Issue by DivineThreepwood** [DivineThreepwood/bcozy#19]
* A system-user-flag is needed to filter the "bco" user or the "client-user" in the bcozy "AvailableUserPane".
* This flag is useful for the ActionConfig generation as well to decide if the action was triggered by a real user or by the system.

**Comment by pLeminoq** [comment]
IsSystemUser flag has been introduced to the UserConfig and can now be used to implement the features mentioned above.
