### ISSUE TITLE
Feature: Register new BCozy instance with public/private key

### ISSUE THREAD

**Issue by Harmageddon** [DivineThreepwood/bcozy#4]
When BCozy is started for the first time, it should provide the option to generate a public/private key pair and add the client to the Registry. 

See also: openbase/bco.authentification#13

**Comment by Harmageddon** [comment]
The new proposed routine for this would be to allow administrators to register the instance of BCozy that they are currently logged in on, via a GUI option.

**Comment by DivineThreepwood** [comment]
Removed from epic because this is not a part of the core framework.

**Comment by DivineThreepwood** [comment]
bcozy development has been freezed.
