### ISSUE TITLE
The BCozy GUI does not start if bco is not reachable.

### ISSUE THREAD

**Issue by DivineThreepwood** [DivineThreepwood/bcozy#57]
This issue seems to be caused by openbase/bco.registry#67

See: https://github.com/openbase/bco.bcozy/blob/5acc549dd0168b0ce8cb5b23d2b45fafa6b81036/src/main/java/org/openbase/bco/bcozy/BCozy.java#L119

**Comment by pLeminoq** [comment]
I removed the referenced part and tested it with and without authentication and it worked fine. So I removed the waitForData once and for all in commit:

* 2eb8dcce1b0e567545c4bb7b3bff29ae040566db
