### ISSUE TITLE
Implement a GUI element in Bcozy to register a user at the BCO Cloud

### ISSUE THREAD

**Issue by pLeminoq** [DivineThreepwood/bcozy#63]
Bcozy should include a GUI component in which a user can activate the cloud connector.
The cloud connector can be activated by using a connect method of the [CloudConnectorRemote](https://github.com/openbase/bco.app/blob/master/cloud-connector/src/main/java/org/openbase/bco/app/cloud/connector/CloudConnectorRemote.java).
In the minimal case the user has to type in a password for his account which will be created at the BCO Cloud.

**Comment by DivineThreepwood** [comment]
bcozy development has been freezed.
