### ISSUE TITLE
Replace Sidebar with Options for Switching Panes and Configuring the View

### ISSUE THREAD

**Issue by rlipperts** [DivineThreepwood/bcozy#69]
Replace the default right sidebar with the configuration options of the power terminal visualization, e.g. granularity, time span, type of visualization, unit.
Only possible configurations are shown.

**Comment by rlipperts** [comment]
Replace the default right sidebar with the configuration options of the power terminal visualization, e.g. granularity, time span, type of visualization, unit.
Only possible configurations are shown.

**Comment by rlipperts** [comment]
Implement functionality for granularity dropdown to finish this

**Comment by DivineThreepwood** [comment]
done
