### ISSUE TITLE
Please checkout if the tilefx charts can be used to visualize the power consumption.

### ISSUE THREAD

**Issue by DivineThreepwood** [DivineThreepwood/bcozy#82]
Since you reported an issue about getting the tilefx demo running, I probably found a solution:

(All details about the demo issue: https://github.com/HanSolo/tilesfx/issues/73)

So please try out if the demo is running on your machine when following this steps:

1. clone the openbase fork of the project:
* ```git clone https://github.com/openbase/tilesfx.git```
* ```cd tilesfx```
2. build the project:
* ```gradle build```
3. start the demo
* ```gradle Demo```

**Comment by SvenjaKenneweg** [comment]
The demo is now working, thanks.
I also added the library to my Intellij project and make the bar chart visualization with tilesfx (See last commit at https://github.com/openbase/bco.bcozy/tree/feature-power-terminal-dashboard). 
By doing this the problem appeared, that the barChart visualization can only have up to 6 entries.

**Comment by DivineThreepwood** [comment]
Now we are using the matrix tile skin to visualize the bars.
The matrix tile skin seems to have a bug where the matrix dots are not using there right datapoint color. However, I just submitted a pull request to solve this issue: https://github.com/HanSolo/tilesfx/pull/75
