### ISSUE TITLE
Merrge branches

### ISSUE THREAD

**Issue by SvenjaKenneweg** [DivineThreepwood/bcozy#88]
Merge all feature_power_terminal_... branches

**Comment by DivineThreepwood** [comment]
hopefully, only the outdated ones. ;)

**Comment by rlipperts** [comment]
heh, didnt realize the pull request was made from a side-branch

**Comment by rlipperts** [comment]
Branches merged back to feature-power-terminal and obsolete feature-power-terminal-dashboard branch deleted
